class dbmanager():

    server_id : str

    def save(self, *args, **kwargs): ...

    def __init__(self, *args, **kwargs): ...
    def get_Server_Config(self, *args, **kwargs): ... 
    def get_command(self, *args, **kwargs): ...
    def get_module(self, *args, **kwargs): ...

    def update_server_config(self, *args, **kwargs): ...
    def update_command(self, *args, **kwargs): ...
    def update_module(self, *args, **kwargs): ...

    def get_leaderboard(self, *args, **kwargs): ...
    def get_user_stats(self, *args, **kwargs): ...

    def update_user_stats(self, *args, **kwargs): ...

    def get_column(self, *args, **kwargs): ...
    def get_row(self, *args, **kwargs): ...

    def update_row(self, *args, **kwargs): ...